/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const CallLog = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'context' : IDL.Text,
  'customerPhone' : IDL.Text,
  'calledAt' : IDL.Int,
});
export const Job = IDL.Record({
  'hp' : IDL.Text,
  'id' : IDL.Text,
  'acType' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'photoUrls' : IDL.Vec(IDL.Text),
  'customerPhone' : IDL.Text,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'photoUrl' : IDL.Opt(IDL.Text),
  'serviceFee' : IDL.Float64,
  'updatedAt' : IDL.Int,
  'customerAddress' : IDL.Text,
  'notes' : IDL.Text,
  'deviceType' : IDL.Text,
  'assignedStaffIds' : IDL.Vec(IDL.Text),
  'brand' : IDL.Text,
  'problem' : IDL.Text,
  'gasType' : IDL.Text,
});
export const PurchaseItem = IDL.Record({
  'id' : IDL.Text,
  'model' : IDL.Text,
  'supplierName' : IDL.Text,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'notes' : IDL.Text,
  'quantity' : IDL.Int,
  'deviceType' : IDL.Text,
  'brand' : IDL.Text,
  'unitPrice' : IDL.Float64,
  'totalPrice' : IDL.Float64,
});
export const SaleItem = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'model' : IDL.Text,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'notes' : IDL.Text,
  'quantity' : IDL.Int,
  'deviceType' : IDL.Text,
  'brand' : IDL.Text,
  'unitPrice' : IDL.Float64,
  'totalPrice' : IDL.Float64,
});
export const Staff = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : IDL.Text,
  'photoUrl' : IDL.Opt(IDL.Text),
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addCallLog' : IDL.Func([CallLog], [], []),
  'addJob' : IDL.Func([Job], [], []),
  'addPurchase' : IDL.Func([PurchaseItem], [], []),
  'addSale' : IDL.Func([SaleItem], [], []),
  'addStaff' : IDL.Func([Staff], [], []),
  'clearCallLogs' : IDL.Func([], [], []),
  'deleteJob' : IDL.Func([IDL.Text], [], []),
  'deletePurchase' : IDL.Func([IDL.Text], [], []),
  'deleteSale' : IDL.Func([IDL.Text], [], []),
  'deleteStaff' : IDL.Func([IDL.Text], [], []),
  'getCallLogs' : IDL.Func([], [IDL.Vec(CallLog)], []),
  'getCredentials' : IDL.Func(
      [],
      [IDL.Record({ 'username' : IDL.Text, 'password' : IDL.Text })],
      [],
    ),
  'getJobs' : IDL.Func([], [IDL.Vec(Job)], []),
  'getPurchases' : IDL.Func([], [IDL.Vec(PurchaseItem)], []),
  'getSales' : IDL.Func([], [IDL.Vec(SaleItem)], []),
  'getStaff' : IDL.Func([], [IDL.Vec(Staff)], []),
  'setCredentials' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateJob' : IDL.Func([Job], [], []),
  'updatePurchase' : IDL.Func([PurchaseItem], [], []),
  'updateSale' : IDL.Func([SaleItem], [], []),
  'updateStaff' : IDL.Func([Staff], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const CallLog = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'context' : IDL.Text,
    'customerPhone' : IDL.Text,
    'calledAt' : IDL.Int,
  });
  const Job = IDL.Record({
    'hp' : IDL.Text,
    'id' : IDL.Text,
    'acType' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'photoUrls' : IDL.Vec(IDL.Text),
    'customerPhone' : IDL.Text,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'photoUrl' : IDL.Opt(IDL.Text),
    'serviceFee' : IDL.Float64,
    'updatedAt' : IDL.Int,
    'customerAddress' : IDL.Text,
    'notes' : IDL.Text,
    'deviceType' : IDL.Text,
    'assignedStaffIds' : IDL.Vec(IDL.Text),
    'brand' : IDL.Text,
    'problem' : IDL.Text,
    'gasType' : IDL.Text,
  });
  const PurchaseItem = IDL.Record({
    'id' : IDL.Text,
    'model' : IDL.Text,
    'supplierName' : IDL.Text,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'notes' : IDL.Text,
    'quantity' : IDL.Int,
    'deviceType' : IDL.Text,
    'brand' : IDL.Text,
    'unitPrice' : IDL.Float64,
    'totalPrice' : IDL.Float64,
  });
  const SaleItem = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'model' : IDL.Text,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'notes' : IDL.Text,
    'quantity' : IDL.Int,
    'deviceType' : IDL.Text,
    'brand' : IDL.Text,
    'unitPrice' : IDL.Float64,
    'totalPrice' : IDL.Float64,
  });
  const Staff = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : IDL.Text,
    'photoUrl' : IDL.Opt(IDL.Text),
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addCallLog' : IDL.Func([CallLog], [], []),
    'addJob' : IDL.Func([Job], [], []),
    'addPurchase' : IDL.Func([PurchaseItem], [], []),
    'addSale' : IDL.Func([SaleItem], [], []),
    'addStaff' : IDL.Func([Staff], [], []),
    'clearCallLogs' : IDL.Func([], [], []),
    'deleteJob' : IDL.Func([IDL.Text], [], []),
    'deletePurchase' : IDL.Func([IDL.Text], [], []),
    'deleteSale' : IDL.Func([IDL.Text], [], []),
    'deleteStaff' : IDL.Func([IDL.Text], [], []),
    'getCallLogs' : IDL.Func([], [IDL.Vec(CallLog)], []),
    'getCredentials' : IDL.Func(
        [],
        [IDL.Record({ 'username' : IDL.Text, 'password' : IDL.Text })],
        [],
      ),
    'getJobs' : IDL.Func([], [IDL.Vec(Job)], []),
    'getPurchases' : IDL.Func([], [IDL.Vec(PurchaseItem)], []),
    'getSales' : IDL.Func([], [IDL.Vec(SaleItem)], []),
    'getStaff' : IDL.Func([], [IDL.Vec(Staff)], []),
    'setCredentials' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateJob' : IDL.Func([Job], [], []),
    'updatePurchase' : IDL.Func([PurchaseItem], [], []),
    'updateSale' : IDL.Func([SaleItem], [], []),
    'updateStaff' : IDL.Func([Staff], [], []),
  });
};

export const init = ({ IDL }) => { return []; };